Added completed task for lesson 16
eugene-okulik/zenevsky pull request #15
Opened 2024-12-15 15:49 UTC by zenevsky

2024-12-16 12:01 UTC, eugene-okulik requested changes

2024-12-16 12:01 UTC, eugene-okulik commented on homework/vladislav_zenevsky/lesson_16/task_1.py
> +cursor.execute(select_query, ('Ivan', 'Petr', 'Mark', 'Petrov', 'Ivanov', 'Pavlov'))
Не нужно хардкодить то, что в файле. Нужно сделать такую программу, которая обработает этот файл и даже если в нем 100 записей появится.

2024-12-16 17:29 UTC, zenevsky commented on homework/vladislav_zenevsky/lesson_16/task_1.py
> +cursor.execute(select_query, ('Ivan', 'Petr', 'Mark', 'Petrov', 'Ivanov', 'Pavlov'))
Окей, убрал срез

2024-12-17 12:02 UTC, eugene-okulik approved these changes
Вот и добрались мы до конца раздела по питону. Теперь сделаем отчетную работу по нему.  
Если будут вопросы по следующему заданию - пиши в телеграм

2024-12-17 12:02 UTC, merged