Added lesson_4.py
eugene-okulik/zenevsky pull request #3
Opened 2024-10-09 19:14 UTC by zenevsky

2024-10-10 08:32 UTC, eugene-okulik requested changes
Всё отлично, кроме одного ключа

2024-10-10 08:32 UTC, eugene-okulik commented on homework/vladislav_zenevsky/lesson_4/lesson_4.py
> +my_dict['dict']['i am a tuple'] = 'you can trust me'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-10-11 15:57 UTC, zenevsky commented on homework/vladislav_zenevsky/lesson_4/lesson_4.py
> +my_dict['dict']['i am a tuple'] = 'you can trust me'
Исправил, посмотри, пожалуйста

2024-10-12 08:38 UTC, eugene-okulik approved these changes

2024-10-12 08:38 UTC, merged